# Basic
title: bigbro
subtitle: 秘密基地，记录成长
welcome_message: hello, 我是王岩，人称大师兄（bigbro），一名iOS客户端开发小白，正在努力成为大神的路上
description: 
creator: <a href="https://github.com/1990yanjing">@bigbro</a>

url: "http://vno.onevcat.com"   

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Github, description: My Projects, url: 'https://github.com/1990yanjing'}
    - {title: 个人简历, description: 个人简历, url: '/docs/index.html'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 1990yanjing
    github: 1990yanjing
    twitter:
    gplus: 
    mail: wangyan_bupt@126.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
